title: "GANStrument: Adversarial Instrument Sound Synthesis with Pitch-invariant Instance Conditioning"
description: Gaku Narita, Junichi Shimizu, and Taketo Akama (Sony Computer Science Laboratories, Tokyo, Japan)
theme: jekyll-theme-cayman
markdown: kramdown
